### ISSUE TITLE
Cannot read all data. Bytes read: 5. Bytes expected: 8

### ISSUE THREAD

**Issue by vinay2897** [ClickHouse/clickhouse-js#166]
### Describe the bug
Unable to insert to AggreagateFunction type of column.

### Steps to reproduce
1. Create table
```
create table test (id String, data AggregateFunction(quantilesBFloat16(0.5), Float32));
```
2. Insert a row
```
await clickhouseClient.insert({
    table: 'test',
    values: [
      {
        id: '1',
        data: `(SELECT quantilesBFloat16State(1)(x) FROM (SELECT arrayJoin([toFloat32(34), toFloat32(12)]) AS x))`,
      },
    ],
    format: 'JSONEachRow',
  });
  ```

### Expected behaviour
Should insert the row.

### Error log
```
\node_modules\@clickhouse\client\dist\error\parse_error.js:32
        return new ClickHouseError(groups);
               ^

ClickHouseError: Cannot read all data. Bytes read: 5. Bytes expected: 8.: (while reading the value of key data): (at row 1)
: While executing ParallelParsingBlockInputFormat.
    at parseError (\node_modules\@clickhouse\client\dist\error\parse_error.js:32:16)
    at ClientRequest.onResponse (\node_modules\@clickhouse\client\dist\connection\adapter\base_http_adapter.js:130:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {  code: '33',
  type: 'CANNOT_READ_ALL_DATA'
}
```

#### Environment
* Client version: 0.0.16
* Language version: Node v18.16.0
* OS: Windows 10

#### ClickHouse server
* ClickHouse Server version: 23.4.2.11

**Comment by slvrtrn** [comment]
Can you please provide an example of an INSERT query that works via `clickhouse-client` with your sample table?

**Comment by vinay2897** [comment]
Hi @slvrtrn 
This is one query that works in `clickhouse-client`
```
insert into test select '1', quantilesBFloat16State(0.5)(arrayJoin([toFloat32(10), toFloat32(20)]));
```
I am unsure how I would run this query using this library

**Comment by slvrtrn** [comment]
@vinay2897, this is complicated using the default `insert` method. I'd suggest using `exec`, which was designed specifically for "unusual" use cases, where you can just pass the entire query:

```ts
await client.exec({
  query: `insert into test select \'1324324\', quantilesBFloat16State(0.5)(arrayJoin([toFloat32(10), toFloat32(20)]))`
})
```
