### ISSUE TITLE
Query fails to parse tuple when provided as an array

### ISSUE THREAD

**Issue by 54m1r** [ClickHouse/clickhouse-js#358]
### Describe the bug

The query fails to work as expected when a query_param of type tuple is provided as an array (e.g., `['foo', 'bar']`). 

### Steps to reproduce
1. Use the code example to select the first tuple element:
2. Observe the error when running the query.

### Expected behaviour

The query should successfully return the first element of the tuple. 
On ClickHouse Cloud Console it's working with `('foo', 'bar')`

### Code example

```
const res = await client.query({
        query: `SELECT tupleElement({tupleParam: Tuple(String, String)}, 1) AS firstElement`,
        query_params: {
          tupleParam: ['foo', 'bar'],
        },
      })
```

### Error log

```
Error: Cannot parse input: expected '(' before: '[\'foo\',\'bar\']': value ['foo','bar'] cannot be parsed as Tuple(String, String) for query parameter 'tupleParam'. 
    at parseError (/Users/xx/xx/node_modules/packages/client-common/src/error/parse_error.ts:30:12)
    at ClientRequest.onResponse (/Users/xx/xx/node_modules/packages/client-node/src/connection/node_base_connection.ts:477:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 code: '27',
 type: 'CANNOT_PARSE_INPUT_ASSERTION_FAILED'
```

#### Environment
* Client version: 1.8.1
* Language version: node v20.11.1
* OS: macOS 14.3

#### ClickHouse server
* ClickHouse Server version: Cloud 24.8

**Comment by slvrtrn** [comment]
Fixed in [1.9.0](https://github.com/ClickHouse/clickhouse-js/releases/tag/1.9.0); please have a look at the [updated query params example](https://github.com/ClickHouse/clickhouse-js/blob/main/examples/query_with_parameter_binding.ts).

**Comment by 54m1r** [comment]
It's working now. Thank you for your quick response :)
