### ISSUE TITLE
Cannot execute query in readonly mode. For queries over HTTP, method GET implies readonly. You should use method POST for modifying queries.

### ISSUE THREAD

**Issue by shankar1525** [ClickHouse/clickhouse-js#362]
### Code example
```js
const { createClient } = require('@clickhouse/client');
// Create a ClickHouse client instance
const client = createClient({
    host: 10.0.0.1
    username: default,
    password: '',
    database: sample_database,
    keep_alive: {
        enabled: true,
        retry_on_expired_socket: true,
      }
});

async function executeInsertQueryPromise(flag, query, params = [], options = {}) {
    try {
        await client.insert({
            table: query,
            values: params,
            format: 'JSONEachRow',
            
        })
        return ;
    } catch (err) {
        console.error('Query execution failed:', err);
        return;
    }
}
```
### Error log
```
Query execution failed: ClickHouseError: default: Cannot execute query in readonly mode. For queries over HTTP, method GET implies readonly. You should use method POST for modifying queries.
     at parseError (/staging_desker_api1/node_modules/@clickhouse/client-common/dist/error/parse_error.js:34:16)
     at ClientRequest.onResponse (/staging_desker_api1/node_modules/@clickhouse/client/dist/connection/node_base_connection.js:106:59)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
   code: '164',
   type: 'READONLY'
 }   
```

#### Environment
* OS: Linux
* @clickhouse/client version: 0.2.10 // tried latest version too

Getting error in linux server when try to insert or modify details

**Comment by slvrtrn** [comment]
Closing this due to inactivity.
If the issue still persists, please feel free to reopen.
